# Generated by Django 5.0.1 on 2024-01-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(default=1234, upload_to='pics'),
            preserve_default=False,
        ),
    ]
