# Generated by Django 5.0.1 on 2024-01-24 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_book_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='img',
            new_name='image',
        ),
    ]
